---
abstract: 'perl client for reg.ru API 2.'
author:
  - 'Polina Shubina <shubina@reg.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regru-API
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  JSON: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Moo: 0
  Net::Ping: 0
  perl: 5.006
resources:
  repository: https://github.com/regru/regru-api-perl
version: 0.02
