---
abstract: 'Perl bindings for Reg.ru API v2'
author:
  - 'Polina Shubina <shubina@reg.ru>'
  - 'Anton Gerasimov <a.gerasimov@reg.ru>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  HTTP::Date: 6.02
  HTTP::Response: 6.04
  IO::Handle: 0
  IPC::Open3: 0
  Test::Fatal: 0.010
  Test::More: 0.98
  Test::Pod: 1.22
  Test::Warnings: 0.010
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regru-API
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Regru::API:
    file: lib/Regru/API.pm
    version: 0.003
  Regru::API::Bill:
    file: lib/Regru/API/Bill.pm
    version: 0.003
  Regru::API::Domain:
    file: lib/Regru/API/Domain.pm
    version: 0.003
  Regru::API::Folder:
    file: lib/Regru/API/Folder.pm
    version: 0.003
  Regru::API::Response:
    file: lib/Regru/API/Response.pm
    version: 0.003
  Regru::API::Role::Client:
    file: lib/Regru/API/Role/Client.pm
    version: 0.003
  Regru::API::Role::Loggable:
    file: lib/Regru/API/Role/Loggable.pm
    version: 0.003
  Regru::API::Role::Namespace:
    file: lib/Regru/API/Role/Namespace.pm
    version: 0.003
  Regru::API::Role::Serializer:
    file: lib/Regru/API/Role/Serializer.pm
    version: 0.003
  Regru::API::Role::UserAgent:
    file: lib/Regru/API/Role/UserAgent.pm
    version: 0.003
  Regru::API::Service:
    file: lib/Regru/API/Service.pm
    version: 0.003
  Regru::API::User:
    file: lib/Regru/API/User.pm
    version: 0.003
  Regru::API::Zone:
    file: lib/Regru/API/Zone.pm
    version: 0.003
requires:
  Carp: 0
  Class::Load: 0
  Data::Dumper: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moo: 0
  Moose: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  perl: 5.008009
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/regru/regru-api-perl/issues
  homepage: https://metacpan.org/release/Regru-API
  repository: git://github.com/regru/regru-api-perl.git
version: 0.003
x_authority: cpan:IMAGO
